app:
  port: 3000
  name: Filestore
  environment: development

database:
  host: localhost
  port: 5432
  username: app_user
  password: app_pass123
  database: app_db

rabbitmq:
  host: localhost
  port: 5672
  username: admin
  password: admin123

minio:
  endpoint: localhost
  port: 9000
  accessKey: minioadmin
  secretKey: minioadmin123

swagger:
  enabled: true
  path: /swagger