app:
  port: 3000
  name: Filestore
  environment: development

database:
  host: localhost
  port: 5432
  username: app_user
  password: app_pass123
  database: app_db

rabbitmq:
  host: localhost
  port: 5672
  username: admin
  password: admin123

minio:
  endpoint: 'localhost:9000'
  region: 'us-east-1'
  useSSL: false
  accessKey: minioadmin
  secretKey: minioadmin123

storageSetting:
  maxChunks: 1000
  maxChunkSize: 10000000 # 10MB
  maxInitChunks: 5


storage:
  bucket: 'email-storage'
  tempBucket: 'email-storage-temp'

swagger:
  enable: true
  path: /swagger